//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaNetworkApp.DataFolder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cinema> Cinema { get; set; }
        public virtual DbSet<CinemaPlace> CinemaPlace { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Films> Films { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<Halls> Halls { get; set; }
        public virtual DbSet<Metro> Metro { get; set; }
        public virtual DbSet<PlaceStatus> PlaceStatus { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Seats> Seats { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<WorkerInfo> WorkerInfo { get; set; }
        public virtual DbSet<Country> Country { get; set; }
    }
}
