
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CinemaNetworkApp.DataFolder
{

using System;
    using System.Collections.Generic;
    
public partial class FilmHire
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public FilmHire()
    {

        this.FilmHireTime = new HashSet<FilmHireTime>();

    }


    public int IdFilmHire { get; set; }

    public int IdFilm { get; set; }

    public System.DateTime DateOfHire { get; set; }



    public virtual Films Films { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FilmHireTime> FilmHireTime { get; set; }

}

}
