
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CinemaNetworkApp.DataFolder
{

using System;
    using System.Collections.Generic;
    
public partial class Films
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Films()
    {

        this.FilmHire = new HashSet<FilmHire>();

        this.Genres = new HashSet<Genres>();

    }


    public int IdFilm { get; set; }

    public string FilmName { get; set; }

    public string FilmDirector { get; set; }

    public System.DateTime DateOfIssue { get; set; }

    public int AgeLimit { get; set; }

    public decimal Rating { get; set; }

    public string Duration { get; set; }

    public byte[] FilmPoster { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FilmHire> FilmHire { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Genres> Genres { get; set; }

}

}
