
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CinemaNetworkApp.DataFolder
{

using System;
    using System.Collections.Generic;
    
public partial class FilmHireTime
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public FilmHireTime()
    {

        this.RowsOfHallsInFilmHireTime = new HashSet<RowsOfHallsInFilmHireTime>();

    }


    public int IdFilmHireTime { get; set; }

    public int IdFilmHire { get; set; }

    public System.TimeSpan Time { get; set; }



    public virtual FilmHire FilmHire { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RowsOfHallsInFilmHireTime> RowsOfHallsInFilmHireTime { get; set; }

}

}
