
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CinemaNetworkApp.DataFolder
{

using System;
    using System.Collections.Generic;
    
public partial class PlacesInRownOFHallsInFilmHireTime
{

    public int IdRowsFilmsHireTime { get; set; }

    public int Number { get; set; }

    public int IdPlaceStatus { get; set; }



    public virtual RowsOfHallsInFilmHireTime RowsOfHallsInFilmHireTime { get; set; }

}

}
