//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaNetworkApp.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seats()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int IdSeat { get; set; }
        public int RowSeatsNumber { get; set; }
        public int SeatNumber { get; set; }
        public int IdHall { get; set; }
        public int IdPlaceStatus { get; set; }
        public decimal Cost { get; set; }
    
        public virtual Halls Halls { get; set; }
        public virtual PlaceStatus PlaceStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
