
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CinemaNetworkApp.DataFolder
{

using System;
    using System.Collections.Generic;
    
public partial class Tickets
{

    public int IdTicket { get; set; }

    public int IdFilm { get; set; }

    public System.DateTime StartingDate { get; set; }

    public int IdHall { get; set; }

    public decimal Cost { get; set; }

    public int IdSeat { get; set; }



    public virtual Seats Seats { get; set; }

}

}
